repositories: 
  - name: stable
    url: https://charts.helm.sh/stable
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: airflow
    url: https://airflow.apache.org
